global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "spring-boot-local"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8080"

  - job_name: "postgres"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]

  - job_name: "timescale"
    static_configs:
      - targets: [ "timescale-exporter:9187" ]

  - job_name: "redis"
    static_configs:
      - targets: [ "redis-exporter:9121" ]

  - job_name: "containers"
    static_configs:
      - targets: [ "cadvisor:8080" ]
