spring:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: digital-twin-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.twins.demo_twins.*"
        spring.json.use.type.headers: false

  datasource:
    url: jdbc:postgresql://localhost:5432/twins
    username: twins_user
    password: twins_pass

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
